In [95]:
import pandas as pd 
import numpy as np

In [96]:
rome_url = "https://data.insideairbnb.com/italy/lazio/rome/2026-06-20/data/listings.csv.gz"

In [97]:
rome_all = pd.read_csv(rome_url, compression="gzip", nrows=5)

print(rome_all.columns.tolist())

['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name', 'description', 'neighborhood_overview', 'picture_url', 'host_id', 'host_url', 'host_profile_id', 'host_profile_url', 'host_name', 'host_since', 'hosts_time_as_user_years', 'hosts_time_as_user_months', 'hosts_time_as_host_years', 'hosts_time_as_host_months', 'host_location', 'host_about', 'host_response_time', 'host_response_rate', 'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url', 'host_picture_url', 'host_neighbourhood', 'host_listings_count', 'host_total_listings_count', 'host_verifications', 'host_has_profile_pic', 'host_identity_verified', 'neighbourhood', 'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude', 'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price', 'price_quote_checkin_date', 'price_quote_checkout_date', 'price_quote_total_price', 'price_quote_price_per_night', 'price_quote_raw', 'minimum_nights', 'maximum_nights', 'minimum_minimum_nights', 'maximum_minimum_nights', 'minimum_maximum_nights', 'maximum_maximum_nights', 'minimum_nights_avg_ntm', 'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability', 'availability_30', 'availability_60', 'availability_90', 'availability_365', 'calendar_last_scraped', 'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d', 'estimated_revenue_l365d', 'first_review', 'last_review', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'license', 'instant_bookable', 'calculated_host_listings_count', 'calculated_host_listings_count_entire_homes', 'calculated_host_listings_count_private_rooms', 'calculated_host_listings_count_shared_rooms', 'reviews_per_month']

In [98]:
columns_needed = [
    "id",
    "latitude",
    "longitude",
    "room_type",
    "property_type",
    "accommodates",
    "bedrooms",
    "bathrooms",
    "minimum_nights",
    "number_of_reviews",
    "review_scores_rating",
    "price",
    "price_quote_price_per_night"
]

In [99]:
rome = pd.read_csv(
    rome_url,
    compression="gzip",
    usecols=columns_needed
)

In [100]:
florence_url = "https://data.insideairbnb.com/italy/toscana/florence/2026-06-26/data/listings.csv.gz"

In [101]:
florence = pd.read_csv(
    florence_url,
    compression="gzip",
    usecols=columns_needed
)

In [102]:
venice_url = "https://data.insideairbnb.com/italy/veneto/venice/2026-06-15/data/listings.csv.gz"

In [103]:
venice = pd.read_csv(
    venice_url,
    compression="gzip",
    usecols=columns_needed
)

In [104]:
naples_url = "https://data.insideairbnb.com/italy/campania/naples/2026-06-25/data/listings.csv.gz"

In [105]:
naples = pd.read_csv(
    naples_url,
    compression="gzip",
    usecols=columns_needed
)

In [106]:
print("Rome:", rome.shape)
print("Florence:", florence.shape)
print("Venice:", venice.shape)
print("Naples:", naples.shape)

Rome: (37084, 13)
Florence: (13472, 13)
Venice: (8766, 13)
Naples: (11575, 13)

In [107]:
rome["city"] = "Rome"
florence["city"] = "Florence"
venice["city"] = "Venice"
naples["city"] = "Naples"

In [108]:
rome.head()

,id,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,price_quote_price_per_night,minimum_nights,number_of_reviews,review_scores_rating,city
0,2737,41.871360,12.482150,Private room,Private room,1,1.5,NaN,$59.52,59.52,31.0,5,4.80,Rome
1,11834,41.895447,12.491181,Entire rental unit,Entire home/apt,2,1.0,1.0,NaN,NaN,2.0,302,4.87,Rome
2,12398,41.925820,12.469280,Entire rental unit,Entire home/apt,3,1.0,2.0,$117.13,117.13,31.0,85,4.90,Rome
3,19965,41.908230,12.452930,Entire condo,Entire home/apt,5,1.0,2.0,$160.60,160.60,2.0,195,4.58,Rome
4,20534,41.889920,12.468230,Entire vacation home,Entire home/apt,4,1.0,1.0,$243.67,243.67,3.0,50,4.48,Rome

In [109]:
florence.head()

,id,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,price_quote_price_per_night,minimum_nights,number_of_reviews,review_scores_rating,city
0,31840,43.77709,11.25216,Private room in serviced apartment,Private room,2,1.0,1.0,$120.00,120.00,1.0,204,4.71,Florence
1,32180,43.76832,11.24348,Entire condo,Entire home/apt,4,2.0,2.0,$165.50,165.50,6.0,46,4.78,Florence
2,39115,43.77525,11.25258,Private room in home,Private room,2,NaN,NaN,$120.00,120.00,2.0,93,4.54,Florence
3,39165,43.77525,11.25258,Private room in home,Private room,2,1.0,NaN,$137.00,137.00,2.0,25,4.43,Florence
4,39822,43.76742,11.24378,Entire rental unit,Entire home/apt,4,1.0,2.0,$102.75,102.75,4.0,38,4.51,Florence

In [110]:
venice.head()

,id,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,price_quote_price_per_night,minimum_nights,number_of_reviews,review_scores_rating,city
0,44056070,45.432450,12.329880,Entire rental unit,Entire home/apt,3,1.0,2.0,NaN,NaN,1.0,65,4.77,Venice
1,1599943729643705680,45.435441,12.342935,Entire rental unit,Entire home/apt,2,1.0,1.0,$235.00,235.00,2.0,11,4.73,Venice
2,597729839212072443,45.439360,12.328960,Entire condo,Entire home/apt,5,2.0,3.0,$284.73,284.73,2.0,9,4.78,Venice
3,20595989,45.440720,12.325670,Entire rental unit,Entire home/apt,2,1.0,1.0,$156.85,156.85,2.0,518,4.85,Venice
4,16551579,45.437160,12.338700,Room in hotel,Private room,2,1.0,1.0,$143.00,143.00,1.0,2,4.50,Venice

In [111]:
naples.head()

,id,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,price,price_quote_price_per_night,minimum_nights,number_of_reviews,review_scores_rating,city
0,36016,40.850498,14.257196,Entire condo,Entire home/apt,3,1.0,1.0,$80.00,80.00,1,150,4.59,Naples
1,63413,40.832160,14.226420,Entire rental unit,Entire home/apt,2,1.0,1.0,$79.00,79.00,3,137,4.64,Naples
2,74364,40.849690,14.252880,Entire condo,Entire home/apt,2,1.0,1.0,$34.97,34.97,31,292,4.89,Naples
3,76993,40.845680,14.226180,Private room in condo,Private room,4,1.0,NaN,$59.50,59.50,1,101,4.96,Naples
4,77009,40.845680,14.226180,Private room in condo,Private room,2,1.0,NaN,$49.50,49.50,2,267,4.89,Naples

In [112]:
final_data = pd.concat(
    [rome, florence, venice, naples],
    ignore_index=True
)

print("Final dataset shape:", final_data.shape)

Final dataset shape: (70897, 14)

In [113]:
final_data.dtypes

id                               int64
latitude                       float64
longitude                      float64
property_type                      str
room_type                          str
accommodates                     int64
bathrooms                      float64
bedrooms                       float64
price                              str
price_quote_price_per_night    float64
minimum_nights                 float64
number_of_reviews                int64
review_scores_rating           float64
city                               str
dtype: object

In [114]:
final_data["price"] = (
    final_data["price"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.replace(",", "", regex=False)
    .astype(float)
)

In [115]:
final_data.to_csv("italy_airbnb_pre_cleaned.csv", index=False)

In [116]:
final_data.dtypes

id                               int64
latitude                       float64
longitude                      float64
property_type                      str
room_type                          str
accommodates                     int64
bathrooms                      float64
bedrooms                       float64
price                          float64
price_quote_price_per_night    float64
minimum_nights                 float64
number_of_reviews                int64
review_scores_rating           float64
city                               str
dtype: object

In [117]:
final_data.shape

(70897, 14)

In [118]:
final_data.isnull().sum()

id                                 0
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms                      11004
bedrooms                       12877
price                           5050
price_quote_price_per_night     5051
minimum_nights                    22
number_of_reviews                  0
review_scores_rating            9020
city                               0
dtype: int64

In [119]:
final_data["bathrooms"].value_counts()

bathrooms
1.0     43879
2.0     11174
3.0      1775
1.5      1544
4.0       462
2.5       382
0.5       195
5.0       162
6.0        94
3.5        94
4.5        37
7.0        25
5.5        24
8.0        10
9.0        10
6.5         6
12.0        4
8.5         3
7.5         3
10.0        3
12.5        1
9.5         1
15.5        1
24.0        1
13.0        1
11.5        1
11.0        1
Name: count, dtype: int64

In [120]:
val_bath = final_data["bathrooms"].dropna()

In [121]:
prob_bath = val_bath.value_counts(normalize=True)

In [122]:
prob_bath

bathrooms
1.0     0.732623
2.0     0.186566
3.0     0.029636
1.5     0.025779
4.0     0.007714
2.5     0.006378
0.5     0.003256
5.0     0.002705
6.0     0.001569
3.5     0.001569
4.5     0.000618
7.0     0.000417
5.5     0.000401
8.0     0.000167
9.0     0.000167
6.5     0.000100
12.0    0.000067
8.5     0.000050
7.5     0.000050
10.0    0.000050
12.5    0.000017
9.5     0.000017
15.5    0.000017
24.0    0.000017
13.0    0.000017
11.5    0.000017
11.0    0.000017
Name: proportion, dtype: float64

In [123]:
nan_bath = final_data[final_data["bathrooms"].isna()].index

In [124]:
nan_bath

Index([   16,    20,    28,    29,    35,    44,    45,    54,    63,    75,
       ...
       70819, 70822, 70840, 70851, 70854, 70864, 70870, 70892, 70894, 70895],
      dtype='int64', length=11004)

In [125]:
final_data.loc[nan_bath, 'bathrooms'] = np.random.choice(
    prob_bath.index,
    size = len(nan_bath),
    p = prob_bath.values
)

In [126]:
final_data["bathrooms"].isnull().sum()

np.int64(0)

In [127]:
final_data.isnull().sum()

id                                 0
latitude                           0
longitude                          0
property_type                      0
room_type                          0
accommodates                       0
bathrooms                          0
bedrooms                       12877
price                           5050
price_quote_price_per_night     5051
minimum_nights                    22
number_of_reviews                  0
review_scores_rating            9020
city                               0
dtype: int64

In [128]:
final_data["bedrooms"].value_counts()

bedrooms
1.0     32404
2.0     18318
3.0      5441
4.0      1241
5.0       358
6.0       140
7.0        36
8.0        21
0.0        14
9.0        14
10.0       10
12.0        5
13.0        3
11.0        3
15.0        2
16.0        2
14.0        2
21.0        1
17.0        1
28.0        1
18.0        1
23.0        1
20.0        1
Name: count, dtype: int64

In [129]:
val_bed = final_data["bedrooms"].dropna()

In [130]:
prob_bed = val_bed.value_counts(normalize=True)

In [131]:
prob_bed

bedrooms
1.0     0.558497
2.0     0.315719
3.0     0.093778
4.0     0.021389
5.0     0.006170
6.0     0.002413
7.0     0.000620
8.0     0.000362
0.0     0.000241
9.0     0.000241
10.0    0.000172
12.0    0.000086
13.0    0.000052
11.0    0.000052
15.0    0.000034
16.0    0.000034
14.0    0.000034
21.0    0.000017
17.0    0.000017
28.0    0.000017
18.0    0.000017
23.0    0.000017
20.0    0.000017
Name: proportion, dtype: float64

In [132]:
nan_bed = final_data[final_data["bedrooms"].isna()].index

In [133]:
nan_bed

Index([    0,     8,    27,    55,    58,    66,    71,    76,    78,    79,
       ...
       70513, 70574, 70582, 70588, 70589, 70620, 70690, 70726, 70783, 70790],
      dtype='int64', length=12877)

In [134]:
final_data.loc[nan_bed, 'bedrooms'] = np.random.choice(
    prob_bed.index,
    size = len(nan_bed),
    p = prob_bed.values
)

In [135]:
final_data["bedrooms"].isnull().sum()

np.int64(0)

In [136]:
final_data.isnull().sum()

id                                0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bedrooms                          0
price                          5050
price_quote_price_per_night    5051
minimum_nights                   22
number_of_reviews                 0
review_scores_rating           9020
city                              0
dtype: int64

In [137]:
final_data["review_scores_rating"].value_counts()

review_scores_rating
5.00    12216
4.88     1646
4.94     1509
4.89     1475
4.86     1468
        ...
3.46        1
3.45        1
2.60        1
3.87        1
3.62        1
Name: count, Length: 172, dtype: int64

In [138]:
val_review = final_data["review_scores_rating"].dropna()

In [139]:
prob_review = val_review.value_counts(normalize=True)

In [140]:
prob_review

review_scores_rating
5.00    0.197424
4.88    0.026601
4.94    0.024387
4.89    0.023838
4.86    0.023724
          ...
3.46    0.000016
3.45    0.000016
2.60    0.000016
3.87    0.000016
3.62    0.000016
Name: proportion, Length: 172, dtype: float64

In [141]:
nan_review = final_data[final_data["review_scores_rating"].isna()].index

In [142]:
final_data.loc[nan_review, 'review_scores_rating'] = np.random.choice(
    prob_review.index,
    size = len(nan_review),
    p = prob_review.values
)

In [143]:
final_data["review_scores_rating"].isnull().sum()

np.int64(0)

In [144]:
final_data.isnull().sum()

id                                0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bedrooms                          0
price                          5050
price_quote_price_per_night    5051
minimum_nights                   22
number_of_reviews                 0
review_scores_rating              0
city                              0
dtype: int64

In [145]:
final_data.shape

(70897, 14)

In [146]:
final_data = final_data.dropna()

In [147]:
final_data.isnull().sum()

id                             0
latitude                       0
longitude                      0
property_type                  0
room_type                      0
accommodates                   0
bathrooms                      0
bedrooms                       0
price                          0
price_quote_price_per_night    0
minimum_nights                 0
number_of_reviews              0
review_scores_rating           0
city                           0
dtype: int64

In [148]:
final_data.shape

(65828, 14)

In [149]:
final_data.dtypes

id                               int64
latitude                       float64
longitude                      float64
property_type                      str
room_type                          str
accommodates                     int64
bathrooms                      float64
bedrooms                       float64
price                          float64
price_quote_price_per_night    float64
minimum_nights                 float64
number_of_reviews                int64
review_scores_rating           float64
city                               str
dtype: object

In [150]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline

In [151]:
numeric_cols = [
    "accommodates",
    "bathrooms",
    "bedrooms",
    "minimum_nights",
    "number_of_reviews",
    "review_scores_rating"
]

In [152]:
categorical_cols = [
    "property_type",
    "room_type",
    "city"
]

In [153]:
X = final_data[numeric_cols + categorical_cols]
y = final_data["price"]

In [154]:
ct = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ), categorical_cols),
        
    ],
    remainder = "passthrough"
)

In [155]:
X_transformed = ct.fit_transform(X)

In [156]:
print(X.shape)
print(X_transformed.shape)

(65828, 9)
(65828, 83)

In [157]:
feature_names = ct.get_feature_names_out()
print(feature_names)
print(len(feature_names))

['cat__property_type_Barn' 'cat__property_type_Boat'
 'cat__property_type_Camper/RV' 'cat__property_type_Casa particular'
 'cat__property_type_Castle' 'cat__property_type_Cave'
 'cat__property_type_Dammuso'
 'cat__property_type_Entire bed and breakfast'
 'cat__property_type_Entire bungalow' 'cat__property_type_Entire cabin'
 'cat__property_type_Entire chalet' 'cat__property_type_Entire condo'
 'cat__property_type_Entire cottage'
 'cat__property_type_Entire guest suite'
 'cat__property_type_Entire guesthouse' 'cat__property_type_Entire home'
 'cat__property_type_Entire home/apt' 'cat__property_type_Entire loft'
 'cat__property_type_Entire place' 'cat__property_type_Entire rental unit'
 'cat__property_type_Entire serviced apartment'
 'cat__property_type_Entire townhouse'
 'cat__property_type_Entire vacation home'
 'cat__property_type_Entire villa' 'cat__property_type_Farm stay'
 'cat__property_type_Houseboat' 'cat__property_type_Private room'
 'cat__property_type_Private room in bed and breakfast'
 'cat__property_type_Private room in boat'
 'cat__property_type_Private room in casa particular'
 'cat__property_type_Private room in castle'
 'cat__property_type_Private room in condo'
 'cat__property_type_Private room in cottage'
 'cat__property_type_Private room in earthen home'
 'cat__property_type_Private room in farm stay'
 'cat__property_type_Private room in guest suite'
 'cat__property_type_Private room in guesthouse'
 'cat__property_type_Private room in home'
 'cat__property_type_Private room in hostel'
 'cat__property_type_Private room in houseboat'
 'cat__property_type_Private room in loft'
 'cat__property_type_Private room in nature lodge'
 'cat__property_type_Private room in pension'
 'cat__property_type_Private room in rental unit'
 'cat__property_type_Private room in resort'
 'cat__property_type_Private room in serviced apartment'
 'cat__property_type_Private room in tiny home'
 'cat__property_type_Private room in tower'
 'cat__property_type_Private room in townhouse'
 'cat__property_type_Private room in vacation home'
 'cat__property_type_Private room in villa'
 'cat__property_type_Room in aparthotel'
 'cat__property_type_Room in bed and breakfast'
 'cat__property_type_Room in boutique hotel'
 'cat__property_type_Room in heritage hotel'
 'cat__property_type_Room in hostel' 'cat__property_type_Room in hotel'
 'cat__property_type_Room in serviced apartment'
 'cat__property_type_Shared room in bed and breakfast'
 'cat__property_type_Shared room in condo'
 'cat__property_type_Shared room in guesthouse'
 'cat__property_type_Shared room in home'
 'cat__property_type_Shared room in hostel'
 'cat__property_type_Shared room in hotel'
 'cat__property_type_Shared room in rental unit' 'cat__property_type_Tent'
 'cat__property_type_Tiny home' 'cat__property_type_Tower'
 'cat__property_type_Windmill' 'cat__room_type_Entire home/apt'
 'cat__room_type_Hotel room' 'cat__room_type_Private room'
 'cat__room_type_Shared room' 'cat__city_Florence' 'cat__city_Naples'
 'cat__city_Rome' 'cat__city_Venice' 'remainder__accommodates'
 'remainder__bathrooms' 'remainder__bedrooms' 'remainder__minimum_nights'
 'remainder__number_of_reviews' 'remainder__review_scores_rating']
83

In [158]:
from sklearn.model_selection import train_test_split


X_train , X_test , y_train , y_test = train_test_split(
    X, y, test_size=0.23, random_state=42)

In [159]:
from sklearn.ensemble import RandomForestRegressor

rf_pipeline = Pipeline([
    ("preprocessor", ct),
    ("model", RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1
    ))
])

In [160]:
rf_pipeline.fit(X_train , y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['property_type', 'room_type',
                                                   'city'])])),
                ('model',
                 RandomForestRegressor(n_estimators=200, n_jobs=-1,
                                       random_state=42))])

In [161]:
y_pred_rf = rf_pipeline.predict(X_test)

In [162]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [163]:
mae_rf = mean_absolute_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
r2_rf = r2_score(y_test, y_pred_rf)

In [164]:
print("Random Forest - MAE:", mae_rf)
print("Random Forest - RMSE:", rmse_rf)
print("Random Forest - R²:", r2_rf)

Random Forest - MAE: 108.08399256150467
Random Forest - RMSE: 624.65840597074
Random Forest - R²: -2.301228013942249

In [165]:
from sklearn.linear_model import LinearRegression

lr_pipeline = Pipeline([
    ("preprocessor", ct),
    ("model", LinearRegression())
])

In [166]:
lr_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['property_type', 'room_type',
                                                   'city'])])),
                ('model', LinearRegression())])

In [167]:
y_pred_lr = lr_pipeline.predict(X_test)

In [168]:
mae_lr = mean_absolute_error(y_test, y_pred_lr)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
r2_lr = r2_score(y_test, y_pred_lr)

In [169]:
print("Linear Regression - MAE:", mae_lr)
print("Linear Regression - RMSE:", rmse_lr)
print("Linear Regression - R²:", r2_lr)

Linear Regression - MAE: 100.51408681687853
Linear Regression - RMSE: 327.18326984034127
Linear Regression - R²: 0.09432470463269549

In [170]:
from sklearn.ensemble import GradientBoostingRegressor

gbr_pipeline = Pipeline([
    ("preprocessor", ct),
    ("model", GradientBoostingRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=3,
        random_state=42
    ))
])

In [171]:
gbr_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['property_type', 'room_type',
                                                   'city'])])),
                ('model',
                 GradientBoostingRegressor(learning_rate=0.05, n_estimators=200,
                                           random_state=42))])

In [172]:
y_pred_gbr = gbr_pipeline.predict(X_test)

In [173]:
mae_gbr = mean_absolute_error(y_test, y_pred_gbr)
rmse_gbr = np.sqrt(mean_squared_error(y_test, y_pred_gbr))
r2_gbr = r2_score(y_test, y_pred_gbr)

In [174]:
print("Gradient Boosting - MAE:", mae_gbr)
print("Gradient Boosting - RMSE:", rmse_gbr)
print("Gradient Boosting - R²:", r2_gbr)

Gradient Boosting - MAE: 94.9934759907299
Gradient Boosting - RMSE: 330.5118964479943
Gradient Boosting - R²: 0.07580303749194306

In [175]:
final_data.to_csv("italy_airbnb_cleaned.csv", index=False)